import {
  cpSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  readlinkSync,
  rmSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs'
import { dirname, isAbsolute, join, relative, sep } from 'node:path'
import { parseFrontmatter, stringifyFrontmatter } from '../lib/frontmatter'
import { listSkills } from './index'

/** Join, refusing any component that escapes `base` (path-traversal guard). */
function safeJoin(base: string, rel: string): string {
  const target = join(base, rel)
  const r = relative(base, target)
  if (r === '..' || r.startsWith(`..${sep}`) || isAbsolute(r)) {
    throw new Error(`unsafe skill name: ${rel}`)
  }
  return target
}

/**
 * Agent → its conventional skills directory (relative to the project root).
 * The canonical skill lives once under `.agents/skills/<name>`; each agent dir gets a
 * (relative) symlink back to it so every agent shares the same base. Extension point:
 * add cursor/codex/etc. here as their skill conventions stabilize.
 */
export const AGENT_DIRS: Record<string, string> = {
  claude: join('.claude', 'skills'),
}

export interface InstallOptions {
  /** Skill name to install (must be a bundled skill). */
  name: string
  /** Project root to write into. */
  dir: string
  /** Copy the real SKILL.md + references/*.md instead of a discovery stub. */
  full?: boolean
  /** Agent skills dirs to link into (keys of AGENT_DIRS). Defaults to ['claude']. */
  agents?: string[]
  /** Copy the skill into each agent dir instead of symlinking (Windows / no-privilege fallback). */
  noSymlink?: boolean
  /** Replace a non-managed entry already present at an agent path. */
  force?: boolean
}

export interface AgentLink {
  agent: string
  /** Absolute path to the agent entry. */
  path: string
  action: 'symlinked' | 'copied' | 'unchanged'
  /** Relative symlink target (present when symlinked/unchanged). */
  target?: string
}

export interface InstallResult {
  name: string
  /** Absolute `.agents/skills/<name>`. */
  canonicalDir: string
  mode: 'stub' | 'full'
  /** Absolute paths written under `canonicalDir`. */
  files: string[]
  links: AgentLink[]
}

/**
 * Render a discovery-stub SKILL.md. It keeps the real `description` (which drives agent
 * activation) and `allowed-tools`, but the body just points at `bctx skills get <name> --full`
 * so the content stays version-matched to the installed CLI and never drifts. Modeled on the
 * agent-browser stub the repo already consumes (`.agents/skills/agent-browser/SKILL.md`).
 */
export function renderStub(name: string, frontmatter: Record<string, unknown>): string {
  const data: Record<string, unknown> = { name }
  if (typeof frontmatter.description === 'string') data.description = frontmatter.description
  if (frontmatter['allowed-tools'] !== undefined) {
    data['allowed-tools'] = frontmatter['allowed-tools']
  }

  const body = `
# ${name}

This file is a discovery stub, not the usage guide. It was generated by \`bctx skill init\`
and intentionally stays tiny so it never drifts. Before using braincontext, load the real,
version-matched content from the installed CLI:

\`\`\`bash
bctx skills get ${name}          # start here — quick-start, when to save, command reference
bctx skills get ${name} --full   # include the reference docs (progressive disclosure)
\`\`\`

The CLI serves skill content that always matches the installed version, so instructions never
go stale. Run \`bctx skills list\` to see every skill available on this version.

## Why braincontext

\`bctx\` is a local-first SQLite store that lets any agent (Claude, Codex, Cursor, ...) **save**
project context and **retrieve** it later over full-text search — so agents stop re-learning the
same facts. See \`bctx skills get ${name} --full\` for the full workflow.
`
  return stringifyFrontmatter(data, body)
}

function isSymlink(p: string): boolean {
  try {
    return lstatSync(p).isSymbolicLink()
  } catch {
    return false
  }
}

function isDir(p: string): boolean {
  try {
    return lstatSync(p).isDirectory()
  } catch {
    return false
  }
}

function listFilesRecursive(dir: string): string[] {
  const out: string[] = []
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, entry.name)
    if (entry.isDirectory()) out.push(...listFilesRecursive(p))
    else out.push(p)
  }
  return out.sort()
}

/** Link (or copy) the canonical skill into a single agent's skills directory. */
function linkAgent(
  agent: string,
  projectRoot: string,
  name: string,
  canonicalDir: string,
  opts: InstallOptions,
): AgentLink {
  const agentDir = AGENT_DIRS[agent]
  if (!agentDir) throw new Error(`Unknown agent "${agent}".`)
  const agentSkillsDir = join(projectRoot, agentDir)
  mkdirSync(agentSkillsDir, { recursive: true })
  const linkPath = safeJoin(agentSkillsDir, name)
  const relTarget = relative(dirname(linkPath), canonicalDir)

  const linkIsSymlink = isSymlink(linkPath)
  const linkExists = linkIsSymlink || existsSync(linkPath)

  if (opts.noSymlink) {
    // Materialize a copy. Replace our own symlink/copy-dir freely (idempotent re-runs);
    // refuse to clobber a stray regular file without --force.
    if (linkExists) {
      if (!linkIsSymlink && !isDir(linkPath) && !opts.force) {
        throw new Error(`${linkPath} already exists (a file). Use --force to replace it.`)
      }
      rmSync(linkPath, { recursive: true, force: true })
    }
    cpSync(canonicalDir, linkPath, { recursive: true })
    return { agent, path: linkPath, action: 'copied' }
  }

  if (linkIsSymlink) {
    // Our managed entry (or a stale one). No-op when it already points at the canonical dir.
    if (readlinkSync(linkPath) === relTarget) {
      return { agent, path: linkPath, action: 'unchanged', target: relTarget }
    }
    unlinkSync(linkPath)
  } else if (linkExists) {
    // A real dir/file — never clobber without explicit consent.
    if (!opts.force) {
      throw new Error(
        `${linkPath} already exists and is not a bctx-managed symlink. Use --force to replace it.`,
      )
    }
    rmSync(linkPath, { recursive: true, force: true })
  }

  symlinkSync(relTarget, linkPath, 'dir')
  return { agent, path: linkPath, action: 'symlinked', target: relTarget }
}

/**
 * Scaffold a bundled skill into the user's project: write the canonical skill under
 * `.agents/skills/<name>` (a discovery stub by default, or the full doc tree with `full`),
 * then link it into each agent's skills dir (relative symlinks, or copies with `noSymlink`).
 * Idempotent. Never touches the store.
 */
export function installSkill(opts: InstallOptions): InstallResult {
  const { name } = opts
  const skill = listSkills().find((s) => s.name === name)
  if (!skill) {
    const available = listSkills()
      .map((s) => s.name)
      .join(', ')
    throw new Error(`No bundled skill named "${name}". Available: ${available || '(none)'}`)
  }

  const agents = opts.agents && opts.agents.length > 0 ? opts.agents : ['claude']
  for (const a of agents) {
    if (!(a in AGENT_DIRS)) {
      throw new Error(`Unknown agent "${a}". Supported: ${Object.keys(AGENT_DIRS).join(', ')}`)
    }
  }

  const canonicalDir = safeJoin(join(opts.dir, '.agents', 'skills'), name)
  mkdirSync(canonicalDir, { recursive: true })

  const mode: 'stub' | 'full' = opts.full ? 'full' : 'stub'
  let files: string[]
  if (mode === 'full') {
    // Copy the real bundled tree (SKILL.md + references/*.md), preserving structure.
    cpSync(skill.dir, canonicalDir, { recursive: true })
    files = listFilesRecursive(canonicalDir)
  } else {
    const bundledFront = parseFrontmatter(readFileSync(join(skill.dir, 'SKILL.md'), 'utf8')).data
    const skillFile = join(canonicalDir, 'SKILL.md')
    writeFileSync(skillFile, renderStub(name, bundledFront), 'utf8')
    files = [skillFile]
  }

  const links = agents.map((agent) => linkAgent(agent, opts.dir, name, canonicalDir, opts))

  return { name, canonicalDir, mode, files, links }
}
